/**
 * Screen 13 healing BGM — exact filenames on R2 (`studio-canvas-ai-storage/bgm/healing/`).
 * Only keys that resolve with HTTP 200 on the public R2 base are included.
 *
 * Not on public R2 yet (re-add when uploaded):
 * - 3,Still Waters (Extend)굿굿 슬로 (2).mp3
 * - 계정10 Gentle Wide Open.mp3 … Whisperer Horizons.mp3 (18 files)
 */
export const HEALING_BGM_FILENAMES: readonly string[] = [
  "1,Gentle Morning Glow.mp3",
  "1,Still Waters (Extend)굿굿 슬로 (3).mp3",
  "10,Calm Reflections (1).mp3",
  "11,Sunshine Smile.mp3",
  "12,Sunshine Smile (1).mp3",
  "13,Heart of Peace.mp3",
  "14,Heart of Peace (1).mp3",
  "15,Golden Path.mp3",
  "16,Golden Path (1).mp3",
  "17,Soft Horizon.mp3",
  "18,Soft Horizon (1).mp3",
  "19,Quiet Joy.mp3",
  // R2 key has no space before "(1)"
  "2,Gentle Morning Glow(1).mp3",
  "20,Quiet Joy (1).mp3",
  "21,Pure Light.mp3",
  "22,Pure Light (1).mp3",
  "23,Daily Calm.mp3",
  "24,Daily Calm (1).mp3",
  "25,Sweet Balance.mp3",
  "26,Sweet Balance (1).mp3",
  "27,Gentle Flow.mp3",
  "28,Gentle Flow (1).mp3",
  "29,Warm Heart.mp3",
  "3,Harmony in the Breeze.mp3",
  "30,Warm Heart (2).mp3",
  "4,Harmony in the Breeze (1).mp3",
  "5,Serene Harmony.mp3",
  "6,Serene Harmony (1).mp3",
  "7,Cozy Moments.mp3",
  "8,Cozy Moments (1).mp3",
  "9,Calm Reflections.mp3",
  "Calm Hearts, Quiet Joy (1).mp3",
  "Calm Hearts, Quiet Joy.mp3",
  "Dreams in the Quiet Glow (1).mp3",
  "Dreams in the Quiet Glow.mp3",
  "Echoes of Balance (1).mp3",
  "Echoes of Balance.mp3",
  "Grateful Glow (1).mp3",
  "Grateful Glow.mp3",
  "Hidden Garden Glow (1).mp3",
  "Hidden Garden Glow.mp3",
  "Inner Harmony (1).mp3",
  "Inner Harmony.mp3",
  "Kindness in the Sunlight (1).mp3",
  "Kindness in the Sunlight.mp3",
  "Light and New (1).mp3",
  "Light and New.mp3",
  "River of Light (1).mp3",
  "River of Light.mp3",
  "Sunlight on Water (1).mp3",
  "Sunlight on Water.mp3",
  "The River Moves (1).mp3",
  "The River Moves.mp3",
  "Through the Light (1).mp3",
  "Through the Light.mp3",
  "아침28 Whispered Horizons.mp3",
  "아침3 Simple Happiness.mp3",
  "아침4 Simple Happiness.mp3",
  "아침5 Harmony in the Breeze.mp3",
  "아침6 Harmony in the Breeze.mp3",
  "아침7 Whispered Light.mp3",
  "아침8 Whispered Light.mp3",
  "아침9 Smile Wide Open.mp3",
];
